### ISSUE TITLE
Text not showing up

### ISSUE THREAD

**Issue by Vagrantin** [whiplashoo/ids_to_text_inkscape#2]
Hello,
First of all thanks a lot for this extension this is exactly what I was looking for unfortunately in my case it doesn’t seems to fully work.
I have done a test on and the ID is correctly extracted as text but it doesn’t show up on my page, even by making sure I’m using a font which does exist on my machine, and my ellipse has been converted to Path.
I did 2 tests so it has been extracted two times.
Here is how it looks like in my test,
![image](https://user-images.githubusercontent.com/19902259/116179951-1a484480-a753-11eb-8b25-3e573bf47049.png)

For reference I’m running Inkscape version 1.0.2 on Windows 10 20H2.

Am I doing something incorrectly ?
Is there a way to debug this Extension ?
With kind regards
Matth

**Comment by whiplashoo** [comment]
I just tested it for Inkscape 1.0.2 and it seems to work fine:


https://user-images.githubusercontent.com/9117427/116194809-06dcaf80-a73a-11eb-9d15-c93f75373ca2.mp4



Since it is a pretty simple script, the only cases where I have seen it fail is when the selected `<path>` has undergone special processing like simplification. There you might have an error thrown because it cannot calculate the path center properly.

This doesn't seem to be the case here of course. Are you doing the same steps as in my video? Could you post the SVG source (XML-like) file after using the tool?

**Comment by Vagrantin** [comment]
Hello,
Thank you for the feedaback, it looks like I’m doing it the same way here is a demo.
https://user-images.githubusercontent.com/19902259/116225386-b6db0880-a78c-11eb-9010-b6f745f939c4.mp4
And here is the test file I have created,

[TestIdsToText.zip](https://github.com/whiplashoo/ids_to_text_inkscape/files/6383754/TestIdsToText.zip)

**Comment by whiplashoo** [comment]
Could you try with the **Font Weight** setting set to `Normal`? I think the issue might be there.

**Comment by Vagrantin** [comment]
Hello,
Just tested with all font weight in `Arial` and still same thing the text element is effectively created, but not showing up.
I have also tested with `Roboto` font in `normal ` and same issue.
Both font are available in the Windows 10.

**Comment by whiplashoo** [comment]
Yeap, it was the Replace text field that caused the issue. When it was left empty, the script would not write the text inside the `<tspan>`. It should be fixed now:

https://github.com/whiplashoo/ids_to_text_inkscape/commit/5f97c97e3f62f954040887f0db391f4e04a1fb10

I also uploaded the new version to the extensions' repository. Please confirm if it works now.

**Comment by Vagrantin** [comment]
Hello,
Effectively the new version does work correctly now. I have tested it from both source github and Inkscape repository thanks a lot !
